#ifndef C4D_SYMBOLS_H
#define C4D_SYMBOLS_H

enum
{
    DLG_INSTANTCE_MAIN          = 1000,

    // DIALOG CONTROLS
    ID_LINK_ABOUT               = 11000,
    ID_LINK_README,
    ID_AUTHOR_TEXT,
    ID_LINK_WEBSITE,
    ID_SUPPORT_ME,
    ID_VERSION_NUMBER,

    ID_INEXCLUDE_LIST           = 10000,
    ID_EXTRACT_BTN,
    ID_PROCESS_BTN,

    ID_PROGRESSBAR              = 10100,
    ID_PROGRESSBAR_TEXT,

    ID_PRECISION                = 10200,
    ID_SAMPLES,
    ID_SEED,
    ID_BLIND_MODE,

    ID_CONSIDER_MATERIALS       = 10301,
    ID_CONSIDER_NORMALS,
    ID_CONSIDER_UVS,

    ID_BLANK                    = 101010,

    IDS_INSTANTCE_NAME          = 20000,
    IDS_INSTANTCE_HELP,

    IDS_ADD_OBJECTS             = 20100,
    IDS_SETTINGS,
    IDS_PRECISION,
    IDS_SAMPLES,
    IDS_SEED,
    IDS_CONSIDER,
    IDS_CONSIDER_MATERIALS,
    IDS_CONSIDER_NORMALS,
    IDS_CONSIDER_UVS,
    IDS_BLIND_MODE,
    IDS_EXTRACT_BTN,
    IDS_PROCESS_BTN,
};

#endif