#ifndef C4D_SYMBOLS_H
#define C4D_SYMBOLS_H

enum
{
    DLG_INSTANTCE_MAIN = 1000,

    // PLUGIN STRINGS
    IDS_INSTANTCE_NAME,
    IDS_INSTANTCE_HELP,

    // DIALOG STRINGS
    IDS_ADD_OBJECTS,
    IDS_SETTINGS,
    IDS_PRECISION,
    IDS_SAMPLES,
    IDS_SEED,
    IDS_CONSIDER,
    IDS_CONSIDER_MATERIALS,
    IDS_CONSIDER_NORMALS,
    IDS_CONSIDER_UVS,
    IDS_BLIND_MODE,
    IDS_PROCESS_BTN,
    
        _DUMMY_ELEMENT_
};

#endif