#ifndef C4D_SYMBOLS_H
#define C4D_SYMBOLS_H

enum
{
    DLG_INSTANTCE_MAIN          = 1000,
    DLG_INSTANTCE_OBJECT_LIST,
    INSTANTCE_ID_VER,

    // DIALOG CONTROLS
    INSTANTCE_ID_OVERALLGRP             	= 2000,
    INSTANTCE_ID_STATICTEXT,
	INSTANTCE_ID_MULTI_LINE_STRINGBOX,
	INSTANTCE_ID_INEXCLUDE_LIST,
	INSTANTCE_ID_PROCESS_BTN,
	INSTANTCE_ID_PROGRESSBAR,
	INSTANTCE_ID_PROGRESSBAR_TEXT,
	INSTANTCE_ID_PRECISION,
	INSTANTCE_ID_SAMPLES,
	INSTANTCE_ID_SEED,
	INSTANTCE_ID_BLIND_MODE,
	INSTANTCE_ID_CONSIDER_MATERIALS,
	INSTANTCE_ID_CONSIDER_NORMALS,
	INSTANTCE_ID_CONSIDER_UVS,

    // PLUGIN STRINGS
    IDS_INSTANTCE_NAME          = 3000,
    IDS_INSTANTCE_HELP,

    // DIALOG STRINGS
    INSTANTCE_IDS_ADD_OBJECTS             = 4000,
    INSTANTCE_IDS_SETTINGS,
    INSTANTCE_IDS_PRECISION,
    INSTANTCE_IDS_SAMPLES,
    INSTANTCE_IDS_SEED,
    INSTANTCE_IDS_CONSIDER,
    INSTANTCE_IDS_CONSIDER_MATERIALS,
    INSTANTCE_IDS_CONSIDER_NORMALS,
    INSTANTCE_IDS_CONSIDER_UVS,
    INSTANTCE_IDS_BLIND_MODE,
    INSTANTCE_IDS_PROCESS_BTN,
    
        _DUMMY_ELEMENT_
};

#endif